# Generated by Django 5.0.6 on 2024-06-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_job_experience_alter_job_mission_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='techno',
            field=models.ManyToManyField(related_name='jobs', to='core.techno'),
        ),
    ]
