# Generated by Django 5.0.6 on 2024-06-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_job_date_alter_job_esn_alter_job_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='techno',
            new_name='technos',
        ),
    ]
