# Generated by Django 5.0.6 on 2024-06-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_techno_job_technos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techno',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
