# Generated by Django 5.0.6 on 2024-07-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_techno_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techno',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
