# Generated by Django 5.0.6 on 2024-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_techno_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='tjm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
